config:
  host: 192.168.1.10
server:
  port: 8081
spring:
  session:
    store-type: redis
  redis:
    port: 6379
    host: ${config.host}
    jedis:
      pool:
        max-active: 100
        min-idle: 20

  activemq:
    broker-url: failover:(tcp://${config.host}:61616)
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 100

dubbo:
  scan:
    base-packages: cn.fan
  application:
    name: account
  config-center:
    timeout: 10000
    address: zookeeper://${config.host}:2181
dfs:
  url: ${config.host}:81
fdfs:
  connectTimeout: 600
  soTimeout: 1500
  thumbImage:
    height: 150
    width: 150
  tracker-list:
    - ${config.host}:12050