server:
  port: 8081
spring:
  session:
    store-type: redis
  redis:
    port: 6379
    host: 192.168.1.24
    jedis:
      pool:
        max-active: 100
        min-idle: 20

  activemq:
    broker-url: tcp://192.168.1.24:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 100

dubbo:
  registry:
    address: zookeeper://192.168.1.24:2181
  scan:
    base-packages: cn.fan
  application:
    name: account
  protocol:
    name: dubbo
    port: 20888
  config-center:
    timeout: 30

dfs:
  url: 192.168.1.24:7867
fdfs:
  connectTimeout: 600
  soTimeout: 1500
  thumbImage:
    height: 150
    width: 150
  tracker-list:
    - 192.168.1.24:12050