config:
  host: 192.168.1.10
spring:
  redis:
    port: 6379
    host: ${config.host}

  activemq:
    broker-url: failover:(tcp://${config.host}:61616)
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: true
      max-connections: 9

alibaba:
  sms:
    regionId: cn-hangzhou
    accessKeyId: LTAI0fHJkcIXZAkH
    accessSecret: y3UfgqD4jp6QWtNhQP7gdpPTPlv61o
    version: 2017-05-25
    domain: dysmsapi.aliyuncs.com
    signName: 兆军装潢
    registry_validata_templatecode: SMS_189235313  #注册用的 验证码 templatecode
    debugmodel: true