config:
  host: 192.168.1.10
dubbo:
  scan:
    base-packages: cn.fan
  application:
    name: server-user
  config-center:
    timeout: 100000
    address: zookeeper://${config.host}:2181
spring:
  redis:
    host: ${config.host}
    port: 6379
    jedis:
      pool:
        max-active: 100
        min-idle: 20
  datasource:
    druid:
      url: jdbc:mysql://${config.host}:3306/zj_decoraction?
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      initial-size: 4

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.fan.model
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
