config:
  host: 192.168.1.10
server:
  port: 7070
spring:
  redis:
    host: ${config.host}
    port: 6379
  session:
    store-type: redis
dubbo:
  scan:
    base-packages: cn.fan
  application:
    name: mbg
  config-center:
    timeout: 10000
    address: zookeeper://${config.host}:2181
