config:
  host: 192.168.1.10
dubbo:
  protocol:
    name: dubbo
    port: 20889
  scan:
    base-packages: cn.fan
  application:
    name: server-goods
  config-center:
    timeout: 10000
    address: zookeeper://${config.host}:2181
spring:
  datasource:
    druid:
      url: jdbc:mysql://${config.host}:3306/zj_decoraction?
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      initial-size: 4

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.fan.model
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
pagehelper:
  helper-dialect: mysql
  reasonable: true
